name: 'Invoke Test on Host and Env'
description: 'Invokes tests on host and specific environment'
inputs:
  host:
    description: 'Host name'
    required: true
  env_index:
    description: 'Environment number'
    required: true
runs:
  using: composite
  steps:
    - name: 'Create Namespace'
      shell: bash
      run: echo "Create namespace ${{ inputs.host }}-${{ inputs.env_index }}"
    - name: print and wait
      env:
        ENV_HOST: ${{ inputs.host }}
        ENV_NUMBER: ${{ inputs.env_index }}
      shell: bash
      run: |
        set -e 
        sh ./job-script.sh
    - name: 'Delete Namespace'
      if: ${{ always() }}
      shell: bash
      run: echo "Delete namespace ${{ inputs.host }}-${{ inputs.env_index }}"