name: Starting Workflow

on:
  workflow_dispatch:
  push:

jobs:
  exec-host-env:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        host: [A, B]
        env_index: [0, 1, 2]
    concurrency: 'env-${{ matrix.env_index }}'
    steps:
      - uses: ./.github/actions/common
        with:
          host: ${{ matrix.host }}
          env_index: ${{ matrix.env_index }}

  completed:
    needs: [ exec-host-env ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env_index: [ 0, 1, 2 ]
    steps:
      - uses: actions/checkout@v3
      - name: Cleanup Env ${{ matrix.env_index}}
        if: ${{ always() }}
        run: echo "Cleanup env-${{ matrix.env_index}}"
  final_cleanup:
    needs: [ completed ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Final Cleanup
        if: ${{ always() }}
        run: echo "Final Cleanup"
