name: Starting Workflow

on:
  workflow_dispatch:
  push:

jobs:
  create-env:
    runs-on: ubuntu-latest
    steps:
      - name: 'Creating cluster'
        shell: bash
        run: echo "Creating cluster"
  exec-host-env:
    name: 'Executing on environments'
    needs: [ create-env ]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        host: [ A, B ]
        env_index: [ 0, 1, 2 ]
    concurrency: 'env-${{ matrix.env_index }}'
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/common
        with:
          host: ${{ matrix.host }}
          env_index: ${{ matrix.env_index }}
  # cleans up the environments
  env-cleanup:
    name: 'Environment Cleanup'
    if: ${{ always() }}
    needs: [ exec-host-env ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env_index: [ 0, 1, 2 ]
    steps:
      - name: 'Cleanup Env ${{ matrix.env_index}}'
        if: ${{ always() }}
        run: echo "Cleanup env-${{ matrix.env_index}}"
  final_cleanup:
    if: ${{ always() }}
    needs: [ env-cleanup ]
    runs-on: ubuntu-latest
    steps:
      - name: Final Cleanup
        if: ${{ always() }}
        run: echo "Final Cleanup"
