name: Starting Workflow

on:
  workflow_dispatch:
  push:

jobs:
  exec-host-env:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        host: [A, B]
        env_index: [0, 1, 2]
    steps:
      - uses: ./.github/workflows/common-workflow.yml
        with:
          host: ${{ matrix.host }}
          env_index: ${{ matrix.env_index }}

  completed-0:
    needs: [ host-A-env-0, host-B-env-0 ]
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup Env 0
        if: ${{ always() }}
        run: echo "Cleanup env-0"
  completed-1:
    needs: [ host-A-env-1, host-B-env-1 ]
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup Env 1
        if: ${{ always() }}
        run: echo "Cleanup env-1"
  completed-2:
    needs: [ host-A-env-2, host-B-env-2 ]
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup Env 2
        if: ${{ always() }}
        run: echo "Cleanup env-2"
  final_cleanup:
    needs: [ completed-0, completed-1, completed-2 ]
    runs-on: ubuntu-latest
    steps:
      - name: Final Cleanup
        if: ${{ always() }}
        run: echo "Final Cleanup"
