name: Common Workflow

# Controls when the workflow will run
on:
  workflow_call:
    inputs:
      host:
        required: true
        type: string
      env_index:
        required: true
        type: string
jobs:
  workflow-tests:
    name: 'host-${{ matrix.host }}-env-${{ inputs.env_index }}'
    concurrency: 'env-${{ inputs.env_index }}'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: print and wait
        env:
          ENV_HOST: ${{ inputs.host }}
          ENV_NUMBER: ${{ inputs.env_index }}
        run: sh ./job-script.sh
