name: Starting Workflow

on:
  workflow_dispatch:
  push:

jobs:
  create-env:
    name: 'Create Test environment'
    runs-on: ubuntu-latest
    steps:
      - name: 'Creating cluster'
        shell: bash
        run: echo "Creating cluster"
  execute-tests:
    name: 'Executing on environments'
    needs: [ create-env ]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        host: [ A, B ]
        env_index: [ 0, 1, 2 ]
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/common
        with:
          host: ${{ matrix.host }}
          env_index: ${{ matrix.env_index }}
  delete-env:
    name: 'Delete Cluster'
    if: ${{ always() }}
    needs: [ execute-tests ]
    runs-on: ubuntu-latest
    steps:
      - name: Final Cleanup
        if: ${{ always() }}
        run: echo "Final Cleanup"
